gaia_rs/gaia/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth.views import LoginView,LogoutView


app_name = 'gaia'

urlpatterns = [
    path('', views.DataCubeListView.as_view(), name='index'),
    path('dataproducts', views.DataProductsListView.as_view(), name='dataproducts'),
    path('map_form/', views.map_form, name='map_form'),
    path('datacube_detail/<int:pk>/', views.datacube_detail, name='datacube_detail'),
    path('process_datacube/<int:pk>/', views.process_datacube, name='process_datacube'),
    path('raster_file/<int:pk>/', views.raster_file, name='raster_file'),
    path('media/raster_files/<str:file_name>/', views.serve_geotiff, name='serve_geotiff'),
    path('get_status/<int:record_id>/', views.get_status, name='get_status'),
    path('get_puntos/<int:record_id>/', views.get_puntos, name='get_puntos'),
    path('media/plot_images/<str:plot_image>/', views.view_png, name='view_png'),
    path('datacube_edit/<int:pk>/', views.datacube_edit, name='datacube_edit'),
    path('delete_geoimage/<int:pk>/', views.delete_geoimage, name='delete_geoimage'),
    path('delete_datacube/<int:pk>/', views.delete_datacube, name='delete_datacube'),
    path('raster_file_download/<int:pk>/', views.raster_file_download, name='raster_file_download'),
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gaia_rs/gaia/forms.py
import json

from django import forms
from django.contrib.gis.forms import PolygonField, OSMWidget
from django.utils.safestring import mark_safe
from .models import DataCube

class CustomSpatialExtentWidget(forms.Widget):
    def render(self, name, value, attrs=None, renderer=None):
        # Customize the HTML markup here
        html = '''
        <head>
      <style>
        .map-container {
            width: 100%;
            height: 600px; /* Adjust the height as needed */
        }
    
    </style>
    </head>
<body>
    <div  class="map-container" id="map"></div>
    <textarea id="id_spatial_extent" class="vSerializedField required" cols="150" rows="10" name="spatial_extent" hidden></textarea>
    <script>
        var map = L.map('map').setView([40.4166, -3.7038400], 6);

        // Add various layers using leaflet-providersESP
         var osmUrl = 'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
            osmAttrib = '&copy; <a href="http://openstreetmap.org/copyright">OpenStreetMap</a> contributors',
            osm = L.tileLayer(osmUrl, { maxZoom: 18, attribution: osmAttrib })

        var pnoa= L.tileLayer.providerESP('PNOA').addTo(map);
        var ngeo=L.tileLayer.providerESP('NombresGeograficos').addTo(map);
        var pnoa_ngeo=L.layerGroup([pnoa,ngeo]);

        var control=L.control.layers({
        'OSM': osm.addTo(map),
        'PNOA': pnoa.addTo(map),
        'PNOA-NGEO': pnoa_ngeo.addTo(map)
        })
        control.addTo(map);
        
         // Initialize the Leaflet Draw control
    var drawnItems = new L.FeatureGroup();
    map.addLayer(drawnItems);

    var drawControl = new L.Control.Draw({
        edit: {
            featureGroup: drawnItems,
            edit: false,
            remove: true,
            poly: {
                allowIntersection: false
            }
        },
        draw: {
            polygon: {
                allowIntersection: false,
                showArea: true,
                metric: ['km', 'm'],
            }
        }
    });
    map.addControl(drawControl);  
    map.on(L.Draw.Event.CREATED, function (event) {
        var layer = event.layer;
 // Extract coordinates and display in the textarea
        var coordinates = layer.toGeoJSON().geometry.coordinates;
        var geojsonPolygon = {type: 'Polygon',coordinates: coordinates};
        document.getElementById('id_spatial_extent').value = JSON.stringify(geojsonPolygon);
        drawnItems.addLayer(layer);
        
    });
    </script>
    </body>
    </html>
</div>'''
        return mark_safe(html)
class DataCubeForm(forms.ModelForm):
    spatial_extent=PolygonField(widget=CustomSpatialExtentWidget)
    class Meta:
        model= DataCube
        fields=['name','temporal_extent_start','temporal_extent_end','max_cloud_cover','dataproduct','spatial_extent']
        widgets={
                'spatial_extent':OSMWidget(),
                 'temporal_extent_end': forms.DateInput(attrs={'type': 'date'}),
                 'temporal_extent_start':forms.DateInput(attrs={'type':'date'}),
                 }
    def clean(self):
        cleaned_data=super().clean()
        temporal_extent_start=cleaned_data.get("temporal_extent_start")
        temporal_extent_end=cleaned_data.get("temporal_extent_end")
        if temporal_extent_start > temporal_extent_end:
            raise forms.ValidationError("Temporal extent start must be before temporal extent end")
        return cleaned_data
class EditDataCubeForm(forms.ModelForm):
    class Meta:
        model= DataCube
        fields=['name','temporal_extent_start','temporal_extent_end','max_cloud_cover','dataproduct','spatial_extent']
        widgets={
                 'temporal_extent_end': forms.DateInput(attrs={'type': 'date'}),
                 'temporal_extent_start':forms.DateInput(attrs={'type':'date'}),
                 }
    exclude_fields=['spatial_extent']
    def clean(self):
        cleaned_data=super().clean()
        temporal_extent_start=cleaned_data.get("temporal_extent_start")
        temporal_extent_end=cleaned_data.get("temporal_extent_end")
        if temporal_extent_start > temporal_extent_end:
            raise forms.ValidationError("Temporal extent start must be before temporal extent end")
        return cleaned_data

gaia_rs/gaia/views.py
import os
import tempfile

import openeo
import rasterio
from django.http import FileResponse, HttpResponseNotFound, JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse

from .filters import DataCubeFilter, DataProductFilter
from .models import MapLayer, GeoImage, DataProduct
from .models import DataCube
from .forms import DataCubeForm, EditDataCubeForm
from django.contrib.gis.geos import Polygon
import json
from .tables import DataCubeTable, DataCubeDetailTable, GeoImageTable, DataProductTable
from django.conf import settings
from django_tables2.views import SingleTableMixin
from django_filters.views import FilterView

def index(request):
    items=DataCube.objects.all()
    table=DataCubeTable(items)
    return render(request, 'index.html',{'table':table,'filter':DataCubeTable.Meta.filterset_class})


def dataproducts(request):
    items=DataProduct.objects.all()
    table=DataProductTable(items)
    return render(request, 'dataproduct_table.html',{'table':table})

class DataProductsListView(SingleTableMixin,FilterView):
    table_class = DataProductTable
    model=DataProduct
    template_name = 'dataproduct_table.html'
    filterset_class = DataProductFilter

class DataCubeListView(SingleTableMixin,FilterView):
    table_class = DataCubeTable
    model=DataCube
    template_name = 'index.html'
    filterset_class = DataCubeFilter

def map_form(request):
    if request.method == 'POST':
        form = DataCubeForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('gaia:index')
    else:
        form=DataCubeForm()

    return render(request,f'map_form.html',{'form':form})

def datacube_detail(request, pk):
    datacube = DataCube.objects.get(pk=pk)
    geoimages=GeoImage.objects.filter(datacube=datacube)
    datacube_table=DataCubeDetailTable([datacube])
    geoimages_table=GeoImageTable(datacube=datacube)
    plot_image=""
    try:
        plot_image=datacube.plot_image.url
    except:
        pass
    polygon_centroid = datacube.spatial_extent.centroid
    center_latitude=polygon_centroid.y
    center_longitude=polygon_centroid.x
    return render(request, 'datacube_detail.html', {'plot_image':plot_image,'geoimages_table':geoimages_table,'datacube_table': datacube_table,'center_latitude':center_latitude,'center_longitude':center_longitude,'datacube':datacube,'geoimages':geoimages})

def raster_file(request,pk):
    geoimage = GeoImage.objects.get(pk=pk)
    polygon_centroid = geoimage.datacube.spatial_extent.centroid
    center_latitude = polygon_centroid.y
    center_longitude = polygon_centroid.x
    return render(request, 'raster_file.html', {'geoimage': geoimage,'center_latitude':center_latitude,'center_longitude':center_longitude})

def process_datacube(request,pk):
    datacube = DataCube.objects.get(pk=pk)
    datacube.status='processing'
    datacube.save()
    datacube.get_ncdf()
    datacube_table=DataCubeDetailTable([datacube])
    geoimages_table=GeoImageTable(datacube=datacube)
    polygon_centroid = datacube.spatial_extent.centroid
    center_latitude = polygon_centroid.y
    center_longitude = polygon_centroid.x

    # dataproduct_script=str(datacube.dataproduct.script)
    # func=getattr(datacube,dataproduct_script)
    # func()

    return render(request, 'datacube_detail.html', {'pk': pk,'datacube_table': datacube_table,'datacube':datacube,'geoimages_table':geoimages_table,'center_latitude':center_latitude,'center_longitude':center_longitude})
    #return render (request,'processing_datacube.html',{'datacube':str(datacube.name)})

def serve_geotiff(request, file_name):
    # Construct the path to the GeoTIFF file
    file_path = os.path.join(settings.MEDIA_ROOT, file_name)

    # Check if the file exists
    if os.path.exists(file_path):
        # Open the file and serve it using FileResponse
        with open(file_path, 'rb') as file:
            response = FileResponse(file)
            return response

    # Handle the case where the file doesn't exist
    return HttpResponseNotFound("File not found")

def get_status(request, record_id):
    # Fetch the updated text for the record with the given ID
    datacube=DataCube.objects.get(pk=record_id)
    status=datacube.status
    if status=='file_downloaded':
        # Create a reverse URL to the datacube detail view
        url = reverse('gaia:datacube_detail', kwargs={'pk': record_id})

        # Create a button element with the redirect URL
        status = """
                   <a href='{}' class='btn btn-primary btn-sm'>Results</a>
               """.format(url)
        datacube.save()
    return HttpResponse(status)

def get_puntos(request,record_id):
    datacube=DataCube.objects.get(pk=record_id)
    status=datacube.status
    puntos=""
    if status=='finished' or status=='created' or status=='error' or status=='' or status=='file_downloaded' or status=='-':
        puntos=""
    else:
        puntos="..."


    return HttpResponse(puntos)

def view_png(request,plot_image):
    file_path = os.path.join(settings.MEDIA_ROOT, plot_image)
    if os.path.exists(file_path):
        with open(file_path, 'rb') as file:
            response = FileResponse(file)
            return response
    else:
        return HttpResponse('File not found', status=404)

def datacube_edit(request,pk):
    if request.method == 'POST':
        form = EditDataCubeForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('gaia:index')

    else:
        datacube = DataCube.objects.get(pk=pk)
        form=EditDataCubeForm(instance=datacube)
        return render(request,f'edit_datacube_form.html', {'form':form})

    return redirect('gaia:index')

def delete_geoimage(request,pk):
    geoimage=GeoImage.objects.get(pk=pk)
    datacube=geoimage.datacube
    geoimage.delete()
    return redirect('gaia:datacube_detail',pk=datacube.pk)

def delete_datacube(request,pk):
    datacube=DataCube.objects.get(pk=pk)
    datacube.delete()
    return redirect('gaia:index')
def raster_file_download(request, pk):
    geoimage = GeoImage.objects.get(pk=pk)
    raster_file_path = geoimage.raster_file.path
    #raster_file_path = r'/Users/pabloalonso/Documents/GitHub/gaia_rs/gaia_rs/media/raster_files/barrios_de_luna_rgb_2023_08_04_27crRcR.tif'
    return FileResponse(open(raster_file_path,'rb'), content_type='application/tif',filename=geoimage.name)

gaia_rs/gaia/templates/base.html
{% load static %}
{% load floppyforms %}
{% load leaflet_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Gaia{% endblock %}</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">

    <!-- Your custom CSS (if any) -->

    <!-- Bootstrap JavaScript and Popper.js (for Bootstrap's dropdowns, modals, etc.) -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.10.2/umd/popper.min.js"></script>
    <link crossorigin="anonymous" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" rel="stylesheet">
    <script crossorigin="anonymous" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/ol@v7.2.2/ol.css" media="all" rel="stylesheet">
    <link href="/static/gis/css/ol3.css" media="all" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/ol@v7.2.2/dist/ol.js"></script>
    <script src="/static/gis/js/OLMapWidget.js"></script>
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.2.4.min.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" />
    <link rel="stylesheet" href="https://unpkg.com/leaflet-draw@1.0.4/dist/leaflet.draw.css" />
    <!-- Install leaflet-providersESP -->
    <!-- Include Leaflet and Leaflet Draw libraries -->
    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>
<!--    <script src="https://unpkg.com/leaflet-draw@1.0.4/dist/leaflet.draw.js"></script>-->
    <script src="https://cdn.jsdelivr.net/gh/dieghernan/leaflet-providersESP/dist/leaflet-providersESP.min.js"></script>


<!--      <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"-->
<!--         integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY="-->
<!--         crossorigin=""/>-->
    <!-- Make sure you put this AFTER Leaflet's CSS -->
<!--    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"-->
<!--         integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo="-->
<!--         crossorigin=""></script>-->

    <!-- Include leaflet-providersESP -->
    <script src="https://cdn.jsdelivr.net/gh/dieghernan/leaflet-providersESP/dist/leaflet-providersESP.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet.draw/1.0.4/leaflet.draw.js"></script>

</head>
</head>
<body>
<!-- Navigation Bar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{%url 'gaia:index'%}">Gaia</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{%url 'gaia:logout'%}">{{ request.user.username }} - Logout</a>
                {% endif %}
                {% if not request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{%url 'gaia:login'%}">Login</a>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{%url 'gaia:index'%}">Datacubes</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{%url 'gaia:map_form'%}">New</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{%url 'gaia:dataproducts'%}">DataProducts</a>
                </li>
                {% if request.user.is_superuser %}
                <li class="nav-item">
                    <a class="nav-link" href="https://openeo.dataspace.copernicus.eu" target="_blank">Copernicus Batch Jobs</a>
                </li>
                {% endif %}

                {% if request.user.is_superuser %}
                 <li class="nav-item">
                    <a class="nav-link" href="/admin">Admin</a>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="mailto:alonsogpablo@gmail.com">Contact</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<!-- Page Content -->
<div class="container mt-4">
    {% block content %}
    {% endblock %}
</div>

{%block footer%}
<!-- Optional: Footer -->
<footer class="bg-dark text-white text-center py-3">
    &copy; 2023 Gaia
</footer>
{%endblock%}

{%block scripts%}
{%endblock%}

</body>
</html>

gaia_rs/gaia/templates/dataproduct_table.html
<!-- index.html -->
{% extends "base.html" %}
{% load static %}
{% load render_table from django_tables2 %}
{% load bootstrap5 %}

{% block content %}
<!DOCTYPE html>
<html>
<head>
    <title>DataProducts</title>
</head>
<body>
    <h1>DataProduct Table</h1>
    {% if filter %}
    <form action="" method="get" class="form form-inline">
        {% bootstrap_form filter.form layout='inline' %}
        {% bootstrap_button 'filter' %}
    </form>
{% endif %}
    {% render_table table 'django_tables2/bootstrap.html' %}
</body>
</html>

{% endblock %}

gaia_rs/gaia/templates/delete_datacube_button.html
<script src="https://unpkg.com/htmx.org@1.9.1/dist/htmx.min.js"></script>

<form action="{% url 'gaia:delete_datacube' record.id %}" method="post">
  {% csrf_token %}
  <input type="hidden" name="pk" value="{{ object.pk }}">
  <button type="submit" class="btn btn-danger btn-sm" >Delete</button>
</form>

gaia_rs/gaia/templates/edit_datacube_button.html
<script src="https://unpkg.com/htmx.org@1.9.1/dist/htmx.min.js"></script>

<form action="{% url 'gaia:datacube_edit' record.id %}" method="get">
  {% csrf_token %}
  <input type="hidden" name="pk" value="{{ object.pk }}">
  <button type="submit" class="btn btn-info btn-sm" >Edit</button>
</form>

gaia_rs/gaia/templates/edit_datacube_form.html
{% extends "base.html" %}
{% block title %}Edit DataCube{% endblock %}
{% block content %}

<body>
<h1>Edit DataCube</h1>
<form method="post">
    {% csrf_token %}
       <div class="d-flex justify-content-end">
            <!-- Bootstrap Button -->
            <button class="btn btn-primary">Save</button>
        </div>
    {{ form.as_p }}

</form>
{% endblock %}

{%block footer%}
{%endblock%}


{%block scripts%}
{%endblock%}

gaia_rs/gaia/templates/index.html
<!-- index.html -->
{% extends "base.html" %}
{% load static %}
{% load render_table from django_tables2 %}
{% load bootstrap5 %}

{% block content %}
<!DOCTYPE html>
<html>
<head>
    <title>Datacubes</title>
</head>
<body>
    <h1>Datacube Table</h1>
    {% if filter %}
    <form action="" method="get" class="form form-inline">
        {% bootstrap_form filter.form layout='inline' %}
        {% bootstrap_button 'filter' %}
    </form>
{% endif %}
    {% render_table table 'django_tables2/bootstrap.html' %}
</body>
</html>

{% endblock %}

gaia_rs/gaia/templates/login.html
{% extends 'base.html' %}

{% block content %}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
{% endblock %}

gaia_rs/gaia/templates/map_form.html
{% extends "base.html" %}
{% block title %}Add a DataCube{% endblock %}
{% block content %}

<body>
<h1>Add a DataCube</h1>
<form method="post">
    {% csrf_token %}
       <div class="d-flex justify-content-end">
            <!-- Bootstrap Button -->
            <button class="btn btn-primary">Submit</button>
        </div>
    {{ form.as_p }}

</form>
{% endblock %}

{%block footer%}
{%endblock%}


{%block scripts%}
{%endblock%}

gaia_rs/gaia/templates/process_datacube_button.html
<!-- view_button.html -->
<a href="{% url 'gaia:process_datacube' record.id %}" class="btn btn-primary btn-sm">Process</a>

gaia_rs/gaia/templates/processing_datacube.html
<!-- index.html -->
{% extends "base.html" %}
{% load static %}
{% load render_table from django_tables2 %}

{% block content %}
<!DOCTYPE html>
<html>
<head>
    <title>Datacubes</title>
</head>
<body>
    Your datacube {{datacube}} is being processed. Please wait.
</body>
</html>

{% endblock %}

gaia_rs/gaia/templates/raster_file.html
<!--{% extends "base.html" %}-->
{% load render_table from django_tables2 %}
{% load static %}
<!--{% load leaflet_tags %}-->
{% block content %}

<!-- datacube_detail.html -->
<!DOCTYPE html>
<html>
<head>
    <title>{{geoimage.datacube.dataproduct.name}}</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.3/dist/leaflet.css"/>
    <style>
        #map {

            height : 800px;
            width : 100%;

        }
    </style>
</head>
<body>
<script src="https://unpkg.com/leaflet@1.0.3/dist/leaflet.js"></script>
<script src="https://unpkg.com/georaster"></script>
<script src="https://unpkg.com/chroma-js"></script>
<script src="https://unpkg.com/georaster-layer-for-leaflet@3.10.0/dist/georaster-layer-for-leaflet.min.js"></script>
<script src="https://cdn.jsdelivr.net/gh/dieghernan/leaflet-providersESP/dist/leaflet-providersESP.min.js"></script>
    <script src="https://unpkg.com/geoblaze"></script>


<h1>{{geoimage.datacube.dataproduct.name}}</h1>
<div id="map" style="width: 100%; height: 600px;"></div>
<script>
    const center_latitude_float = parseFloat({{center_latitude}}); //convert lat string to number
    const center_longitude_float = parseFloat({{center_longitude}});
    var map = L.map('map').setView([center_latitude_float,center_longitude_float ], 10); // Set your initial map view

    var osmUrl = 'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
        osmAttrib = '&copy; <a href="http://openstreetmap.org/copyright">OpenStreetMap</a> contributors',
        osm = L.tileLayer(osmUrl, { maxZoom: 18, attribution: osmAttrib })

    var pnoa= L.tileLayer.providerESP('PNOA')
    var ngeo=L.tileLayer.providerESP('NombresGeograficos')
    var pnoa_ngeo=L.layerGroup([pnoa,ngeo]);

    var url_to_geotiff_file = "{{geoimage.raster_file.name}}";

    fetch("/media/"+url_to_geotiff_file)
        .then(response => response.arrayBuffer())
        .then(arrayBuffer => {
            parseGeoraster(arrayBuffer).then(georaster => {

                var layer = new GeoRasterLayer({
                    attribution: "GEBCO & Tom Patterson",
                    georaster: georaster,
                    opacity: 0.75,
                    resolution: 512,

                });

                var pnoa_geo=L.layerGroup([pnoa,layer]).addTo(map);
                var osm_geo=L.layerGroup([osm,layer]);

                var control=L.control.layers({
                    'OSM_GeoImage': osm_geo.addTo(map),
                    'PNOA-GeoImage': pnoa_geo.addTo(map)
                })
                control.addTo(map);

                map.fitBounds(layer.getBounds());

map.on('click', e => {
    const lnglat = [e.latlng.lng, e.latlng.lat];
    const latlng = [e.latlng.lat, e.latlng.lng];
    // results is an array, which each item representing a separate band
    const results = geoblaze.identify(georaster, lnglat);
    const formattedResults = results.map(result => parseFloat(result.toFixed(2)));
    // Create a popup with the identification results
    const normalizedResults = formattedResults / 255;
    const popup = L.popup()
        .setLatLng(latlng)
        .setContent(`{{geoimage.datacube.dataproduct.name}}:<br>${JSON.stringify(normalizedResults.toFixed(2))}`)
        .openOn(map);
});

                });
            });








</script>
<!-- Add other fields as needed -->
</body>

{% endblock %}

gaia_rs/gaia/templates/raster_save_button.html
<script src="https://unpkg.com/htmx.org@1.9.1/dist/htmx.min.js"></script>

<form action="{% url 'gaia:raster_file_download' record.id %}" method="post">
  {% csrf_token %}
  <input type="hidden" name="pk" value="{{ object.pk }}">
  <button type="submit" class="btn btn-secondary btn-sm" >Save</button>
</form>

gaia_rs/gaia/templates/status.html
<div id="status">-</div>
<marquee direction="right"
         behavior="alternate" id="puntos"></marquee>

<span hx-target="#status" hx-get="/get_status/{{record.id}}" hx-trigger="every 10s">
    </span>

<span hx-target="#puntos" hx-get="/get_puntos/{{record.id}}" hx-trigger="every 10s">
    </span>

gaia_rs/gaia/templates/view_datacubes.html
<html>
<head>
<title>WMTS Map</title>
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
     integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY="
     crossorigin=""/>
 <!-- Make sure you put this AFTER Leaflet's CSS -->
 <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
     integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo="
     crossorigin=""></script>

 <!-- Install leaflet-providersESP -->
	<script src="https://cdn.jsdelivr.net/gh/dieghernan/leaflet-providersESP/dist/leaflet-providersESP.min.js"></script>


</head>
<body>
<div id="map" style="width:100%; height: 100%"></div>
<script>
    var map = L.map('map').setView([40.4166, -3.7038400], 6);
    // var wmtsLayer = L.tileLayer('{{map_layer.url}}', {
    //     maxZoom:19,
    //     attribution: '{{map_layer.attribution}}',
    //     description:'{{map_layer.description}}'
    // }).addTo(map);
    //L.tileLayer.providerESP('IDErioja').addTo(map);
    L.tileLayer.providerESP('PNOA').addTo(map);
    L.tileLayer.providerESP('MDT.CurvasNivel').addTo(map);
    L.tileLayer.providerESP('NombresGeograficos').addTo(map);
    //L.tileLayer.providerESP('LiDAR').addTo(map);
    //L.tileLayer.providerESP('Copernicus').addTo(map);



</script>
</body>
</html>